// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBtavZjmKNVcdt1x64Enva5eBMMsvd-uo',
    appId: '1:454113896172:web:fa35c487c2f02a60df67c9',
    messagingSenderId: '454113896172',
    projectId: 'chatapp-29aac',
    authDomain: 'chatapp-29aac.firebaseapp.com',
    storageBucket: 'chatapp-29aac.firebasestorage.app',
    measurementId: 'G-WD0JZ5WD5J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5un2Bo-s-eJi6r-oTgJsS4SXZAQPAQYs',
    appId: '1:454113896172:android:f772abfcaa8d9b84df67c9',
    messagingSenderId: '454113896172',
    projectId: 'chatapp-29aac',
    storageBucket: 'chatapp-29aac.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0fuE4hDXL0KJ-BUOwzUK0-THthn1UbdI',
    appId: '1:454113896172:ios:3bf6588696ef826edf67c9',
    messagingSenderId: '454113896172',
    projectId: 'chatapp-29aac',
    storageBucket: 'chatapp-29aac.firebasestorage.app',
    iosBundleId: 'com.example.chatFirebase',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0fuE4hDXL0KJ-BUOwzUK0-THthn1UbdI',
    appId: '1:454113896172:ios:3bf6588696ef826edf67c9',
    messagingSenderId: '454113896172',
    projectId: 'chatapp-29aac',
    storageBucket: 'chatapp-29aac.firebasestorage.app',
    iosBundleId: 'com.example.chatFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDBtavZjmKNVcdt1x64Enva5eBMMsvd-uo',
    appId: '1:454113896172:web:423238b8c9446953df67c9',
    messagingSenderId: '454113896172',
    projectId: 'chatapp-29aac',
    authDomain: 'chatapp-29aac.firebaseapp.com',
    storageBucket: 'chatapp-29aac.firebasestorage.app',
    measurementId: 'G-XPK6FWL2ZC',
  );
}
